import 'package:kovalingo/classes/word_data_class.dart';

class WordPackages {
  List<WordData> a1Word = [
    WordData(
      turkishWord: "elma",
      englishWord: "apple",
      turkishSentence: "Ben bir elma yiyorum.",
      englishSentence: "I am eating an apple.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "masa",
      englishWord: "table",
      turkishSentence: "Kitabım masanın üzerinde.",
      englishSentence: "My book is on the table.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "kitap",
      englishWord: "book",
      turkishSentence: "Okulda çok kitap var.",
      englishSentence: "There are many books at school.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "kalem",
      englishWord: "pen",
      turkishSentence: "Kalemi nerede gördün?",
      englishSentence: "Where did you see the pen?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "kedi",
      englishWord: "cat",
      turkishSentence: "Sokakta bir kedi var.",
      englishSentence: "There is a cat on the street.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "köpek",
      englishWord: "dog",
      turkishSentence: "Köpeğimizi parka götürelim.",
      englishSentence: "Let's take our dog to the park.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "top",
      englishWord: "ball",
      turkishSentence: "Topu bana at.",
      englishSentence: "Throw the ball to me.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "araba",
      englishWord: "car",
      turkishSentence: "Arabayla şehir turu yapalım.",
      englishSentence: "Let's take a city tour by car.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "ev",
      englishWord: "house",
      turkishSentence: "Bizim evimiz yeşil.",
      englishSentence: "Our house is green.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "okul",
      englishWord: "school",
      turkishSentence: "Yarın okula gitmem gerekiyor.",
      englishSentence: "I have to go to school tomorrow.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "film",
      englishWord: "movie",
      turkishSentence: "Bu hafta sonu bir film izleyelim.",
      englishSentence: "Let's watch a movie this weekend.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "para",
      englishWord: "money",
      turkishSentence: "Daha fazla para kazanmalıyım.",
      englishSentence: "I need to earn more money.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "saat",
      englishWord: "clock",
      turkishSentence: "Saat kaç?",
      englishSentence: "What time is it?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "yemek",
      englishWord: "food",
      turkishSentence: "Bugün ne yemek istersin?",
      englishSentence: "What do you want to eat today?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "su",
      englishWord: "water",
      turkishSentence: "Bir bardak su alabilir miyim?",
      englishSentence: "Can I have a glass of water?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "kitaplık",
      englishWord: "bookshelf",
      turkishSentence: "Kitaplarımız kitaplığın üzerinde.",
      englishSentence: "Our books are on the bookshelf.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "yatak",
      englishWord: "bed",
      turkishSentence: "Yatağın üzerinde uyuyor.",
      englishSentence: "He is sleeping on the bed.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "ayakkabı",
      englishWord: "shoe",
      turkishSentence: "Yeni ayakkabılar aldım.",
      englishSentence: "I bought new shoes.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "telefon",
      englishWord: "phone",
      turkishSentence: "Telefonum nerede?",
      englishSentence: "Where is my phone?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "anne",
      englishWord: "mother",
      turkishSentence: "Annem yemek pişiriyor.",
      englishSentence: "My mother is cooking.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "baba",
      englishWord: "father",
      turkishSentence: "Babam işe gitti.",
      englishSentence: "My father went to work.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "kardeş",
      englishWord: "sibling",
      turkishSentence: "Benim iki kardeşim var.",
      englishSentence: "I have two siblings.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "arkadaş",
      englishWord: "friend",
      turkishSentence: "En iyi arkadaşımı kaybettim.",
      englishSentence: "I lost my best friend.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "paraşüt",
      englishWord: "parachute",
      turkishSentence: "Bir gün paraşütle atlamak istiyorum.",
      englishSentence: "I want to skydive one day.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "gözlük",
      englishWord: "glasses",
      turkishSentence: "Gözlüklerini neden takmıyorsun?",
      englishSentence: "Why aren't you wearing your glasses?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "kız",
      englishWord: "girl",
      turkishSentence: "O güzel bir kız.",
      englishSentence: "She is a beautiful girl.",
      imagePath: '',
    ),
  ];
  List<WordData> softwareTerms = [
    WordData(
      turkishWord: "Algoritma",
      englishWord: "Algorithm",
      turkishSentence:
          "Algoritmalar, belirli bir problemi çözmek veya belirli bir görevi yerine getirmek için tasarlanmış adımların bir sırasıdır.",
      englishSentence:
          "Algorithms are a sequence of steps designed to solve a specific problem or perform a specific task.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Değişken",
      englishWord: "Variable",
      turkishSentence:
          "Değişkenler, bir değeri depolamak için kullanılan ve program içinde adlandırılmış bir bellek alanıdır.",
      englishSentence:
          "Variables are named memory locations used to store a value within a program.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Fonksiyon",
      englishWord: "Function",
      turkishSentence:
          "Fonksiyonlar, belirli bir işlevi gerçekleştiren ve genellikle parametreler alarak bir sonuç döndüren kod bloklarıdır.",
      englishSentence:
          "Functions are code blocks that perform a specific task and usually return a result by taking parameters.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Döngü",
      englishWord: "Loop",
      turkishSentence:
          "Döngüler, belirli bir işlemi tekrar tekrar yapmak için kullanılan yapıdır. Örneğin, for ve while döngüleri.",
      englishSentence:
          "Loops are structures used to repeatedly perform a certain task. For example, for and while loops.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Koşullu İfadeler",
      englishWord: "Conditional Statements",
      turkishSentence:
          "Koşullu ifadeler, belirli bir koşulu karşılayıp karşılamadığını kontrol eden ve buna göre farklı işlemleri gerçekleştiren ifadelerdir. Örneğin, if, else if ve else ifadeleri.",
      englishSentence:
          "Conditional statements are statements that check whether a specific condition is met and perform different actions accordingly. For example, if, else if, and else statements.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Sınıf ve Nesne",
      englishWord: "Class and Object",
      turkishSentence:
          "Sınıflar, benzer özelliklere ve işlevlere sahip nesnelerin bir şablonudur. Bir sınıfın örneğine ise nesne denir.",
      englishSentence:
          "Classes are templates for objects that have similar properties and behaviors. An instance of a class is called an object.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Modül/Paket",
      englishWord: "Module/Package",
      turkishSentence:
          "Kodunuzu düzenlemek için kullanılan ve farklı dosyalara bölünebilen kod kütüphaneleridir.",
      englishSentence:
          "Modules/Packages are code libraries used to organize your code and can be divided into different files.",
      imagePath: '',
    ),
  ];
  List<WordData> prepositions = [
    WordData(
      turkishWord: "in",
      englishWord: "içinde",
      turkishSentence: "Kutu dolabın içinde.",
      englishSentence: "The box is in the cupboard.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "on",
      englishWord: "üzerinde",
      turkishSentence: "Kitap masanın üstünde.",
      englishSentence: "The book is on the table.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "at",
      englishWord: "de",
      turkishSentence: "Kız okulda.",
      englishSentence: "The girl is at school.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "by",
      englishWord: "tarafından",
      turkishSentence: "Ben evdeyim.",
      englishSentence: "I am by the house.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "for",
      englishWord: "için",
      turkishSentence: "Hediye babam için.",
      englishSentence: "The gift is for my father.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "with",
      englishWord: "ile",
      turkishSentence: "Benimle gel.",
      englishSentence: "Come with me.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "from",
      englishWord: "den",
      turkishSentence: "Sarı çiçek bahçeden.",
      englishSentence: "The yellow flower is from the garden.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "to",
      englishWord: "e",
      turkishSentence: "Okula gidiyorum.",
      englishSentence: "I am going to school.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "into",
      englishWord: "içine",
      turkishSentence: "Köpek kutuya giriyor.",
      englishSentence: "The dog is going into the box.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "under",
      englishWord: "altında",
      turkishSentence: "Kedi masanın altında.",
      englishSentence: "The cat is under the table.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "over",
      englishWord: "üzerinden",
      turkishSentence: "Uçak bulutların üzerinden geçiyor.",
      englishSentence: "The plane is flying over the clouds.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "between",
      englishWord: "arasında",
      turkishSentence: "İki ağaç arasında.",
      englishSentence: "Between two trees.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "among",
      englishWord: "arasında",
      turkishSentence: "Arkadaşlarım arasında.",
      englishSentence: "Among my friends.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "against",
      englishWord: "karşısında",
      turkishSentence: "Duvara karşı.",
      englishSentence: "Against the wall.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "off",
      englishWord: "üzerinden",
      turkishSentence: "Işıkları kapat.",
      englishSentence: "Turn the lights off.",
      imagePath: '',
    ),
  ];
  List<WordData> holidayPhrases = [
    WordData(
      turkishWord: "Bir tatil köyünde kalmayı tercih ediyoruz.",
      englishWord: "We prefer to stay at a resort.",
      turkishSentence: "Bir tatil köyünde kalmayı tercih ediyoruz.",
      englishSentence: "We prefer to stay at a resort.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Bir şezlongda güneşlenmek istiyorum.",
      englishWord: "I want to sunbathe on a lounge chair.",
      turkishSentence: "Bir şezlongda güneşlenmek istiyorum.",
      englishSentence: "I want to sunbathe on a lounge chair.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Deniz kenarında yürüyüş yapmak çok rahatlatıcı.",
      englishWord: "Taking a walk by the seaside is very relaxing.",
      turkishSentence: "Deniz kenarında yürüyüş yapmak çok rahatlatıcı.",
      englishSentence: "Taking a walk by the seaside is very relaxing.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Akşam yemeği için lezzetli bir deniz ürünleri restoranı arıyoruz.",
      englishWord: "We're looking for a delicious seafood restaurant for dinner.",
      turkishSentence: "Akşam yemeği için lezzetli bir deniz ürünleri restoranı arıyoruz.",
      englishSentence: "We're looking for a delicious seafood restaurant for dinner.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Güneş kremi sürmeyi unutma, aksi halde güneş yanığı olabilirsin.",
      englishWord: "Don't forget to apply sunscreen, otherwise you might get sunburned.",
      turkishSentence: "Güneş kremi sürmeyi unutma, aksi halde güneş yanığı olabilirsin.",
      englishSentence: "Don't forget to apply sunscreen, otherwise you might get sunburned.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Şnorkelle dalış yapmak için mükemmel bir yer buldum.",
      englishWord: "I found a perfect spot for snorkeling.",
      turkishSentence: "Şnorkelle dalış yapmak için mükemmel bir yer buldum.",
      englishSentence: "I found a perfect spot for snorkeling.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Sıcak havada serinlemek için denize girelim.",
      englishWord: "Let's go for a swim to cool off in the hot weather.",
      turkishSentence: "Sıcak havada serinlemek için denize girelim.",
      englishSentence: "Let's go for a swim to cool off in the hot weather.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Bisikletle adanın etrafını dolaşmak istiyorum.",
      englishWord: "I want to bike around the island.",
      turkishSentence: "Bisikletle adanın etrafını dolaşmak istiyorum.",
      englishSentence: "I want to bike around the island.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Plajda güneşin tadını çıkarmak için sabırsızlanıyorum.",
      englishWord: "I can't wait to enjoy the sun at the beach.",
      turkishSentence: "Plajda güneşin tadını çıkarmak için sabırsızlanıyorum.",
      englishSentence: "I can't wait to enjoy the sun at the beach.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "Tatile giderken bol bol fotoğraf çekmek istiyorum.",
      englishWord: "I want to take lots of photos while on vacation.",
      turkishSentence: "Tatile giderken bol bol fotoğraf çekmek istiyorum.",
      englishSentence: "I want to take lots of photos while on vacation.",
      imagePath: '',
    ),
  ];
  List<WordData> b1Words = [
    WordData(
      turkishWord: "hızlı",
      englishWord: "fast",
      turkishSentence: "O çok hızlı koşuyor.",
      englishSentence: "He is running very fast.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "geç",
      englishWord: "late",
      turkishSentence: "Trenimiz gecikti.",
      englishSentence: "Our train is late.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "sağlık",
      englishWord: "health",
      turkishSentence: "Sağlık her şeyden önemlidir.",
      englishSentence: "Health is more important than anything.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "alışveriş",
      englishWord: "shopping",
      turkishSentence: "Bugün alışverişe gidelim mi?",
      englishSentence: "Shall we go shopping today?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "ziyaret",
      englishWord: "visit",
      turkishSentence: "Yarın annemi ziyaret edeceğim.",
      englishSentence: "I will visit my mother tomorrow.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "kiralık",
      englishWord: "rental",
      turkishSentence: "Bu ev kiralık mı?",
      englishSentence: "Is this house for rent?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "doğru",
      englishWord: "correct",
      turkishSentence: "Bu cevap doğru mu?",
      englishSentence: "Is this answer correct?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "yanlış",
      englishWord: "wrong",
      turkishSentence: "Maalesef yanlış yoldayız.",
      englishSentence: "Unfortunately, we are on the wrong road.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "boş",
      englishWord: "empty",
      turkishSentence: "Bu kutu boş mu dolu mu?",
      englishSentence: "Is this box empty or full?",
      imagePath: '',
    ),
    WordData(
      turkishWord: "sıcak",
      englishWord: "hot",
      turkishSentence: "Bugün hava çok sıcak.",
      englishSentence: "Today the weather is very hot.",
      imagePath: '',
    ),
  ];
  List<WordData> c2Words = [
    WordData(
      turkishWord: "mükemmellik",
      englishWord: "excellence",
      turkishSentence: "Şirketimiz mükemmellik ödülü kazandı.",
      englishSentence: "Our company won an excellence award.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "olumlu",
      englishWord: "positive",
      turkishSentence: "Sonuçlar oldukça olumlu.",
      englishSentence: "The results are quite positive.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "çekirdek",
      englishWord: "nucleus",
      turkishSentence: "Atomun çekirdeği oldukça küçüktür.",
      englishSentence: "The nucleus of an atom is very small.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "çeşitlilik",
      englishWord: "diversity",
      turkishSentence: "Bu şehirde kültürel çeşitlilik var.",
      englishSentence: "There is cultural diversity in this city.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "çeşitlendirme",
      englishWord: "diversification",
      turkishSentence: "Şirket stratejik çeşitlendirme planlarını değerlendiriyor.",
      englishSentence: "The company is evaluating strategic diversification plans.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "eleştirel",
      englishWord: "critical",
      turkishSentence: "Bu rapor oldukça eleştirel bir analiz sunuyor.",
      englishSentence: "This report provides a critical analysis.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "zenginleştirme",
      englishWord: "enrichment",
      turkishSentence: "Bu ders materyal zenginleştirmesi içerir.",
      englishSentence: "This lesson includes material enrichment.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "tezat",
      englishWord: "contradiction",
      turkishSentence: "Görüşler arasında tezat var.",
      englishSentence: "There is a contradiction between the views.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "berraklık",
      englishWord: "clarity",
      turkishSentence: "Sunumunuzdaki berraklık takdir edildi.",
      englishSentence: "The clarity in your presentation was appreciated.",
      imagePath: '',
    ),
    WordData(
      turkishWord: "mahrumiyet",
      englishWord: "privation",
      turkishSentence: "Yoksulluk nedeniyle birçok mahrumiyet yaşadı.",
      englishSentence: "He experienced many privations due to poverty.",
      imagePath: '',
    ),
  ];
}
