// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq-jL7OnTrM96I0mH7o7cVs0s8uGigqfw',
    appId: '1:1049894761843:web:fb4d47a8842f96a8268106',
    messagingSenderId: '1049894761843',
    projectId: 'kovalingoo',
    authDomain: 'kovalingoo.firebaseapp.com',
    storageBucket: 'kovalingoo.appspot.com',
    measurementId: 'G-LC7JB074NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHBUBR9_bUtvHyuS7ec7mjYr1sIMJwrU',
    appId: '1:1049894761843:android:8c71a4bdbf26747c268106',
    messagingSenderId: '1049894761843',
    projectId: 'kovalingoo',
    storageBucket: 'kovalingoo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCehTL0zHEh1Y8VEclZrpE2G-NSPQwfmv0',
    appId: '1:1049894761843:ios:ab4bb2395ea289de268106',
    messagingSenderId: '1049894761843',
    projectId: 'kovalingoo',
    storageBucket: 'kovalingoo.appspot.com',
    iosBundleId: 'com.example.kovalingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCehTL0zHEh1Y8VEclZrpE2G-NSPQwfmv0',
    appId: '1:1049894761843:ios:604bc58f504863ad268106',
    messagingSenderId: '1049894761843',
    projectId: 'kovalingoo',
    storageBucket: 'kovalingoo.appspot.com',
    iosBundleId: 'com.example.kovalingo.RunnerTests',
  );
}
